services:
  caseshelf:
    image: havocwyrm/caseshelf:latest
    container_name: caseshelf
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - caseshelf_data:/app/data
