export const platformLogoMap: Record<string, string> = {
    "PS1": "/platformLogos/ps1Logo.svg",
    "PS2": "/platformLogos/ps2Logo.svg",
    "PS3": "/platformLogos/ps3Logo.svg",
    "PS4": "/platformLogos/ps4Logo.svg",
    "PS5": "/platformLogos/ps5Logo.svg",
    "PSP": "/platformLogos/pspLogo.svg",
    "PS Vita": "/platformLogos/psvitaLogo.svg",
    "Xbox": "/platformLogos/xboxLogo.svg",
    "Xbox 360": "/platformLogos/xbox360Logo.svg",
    "Xbox One": "/platformLogos/xboxoneLogo.svg",
    "Xbox Series X|S": "/platformLogos/xboxseriesXLogo.svg",
    "Nintendo Entertainment System (NES)": "/platformLogos/nesLogo.svg",
    "Super Nintendo (SNES)": "/platformLogos/snesLogo.svg",
    "Nintendo 64": "/platformLogos/nintendo64Logo.svg",
    "GameCube": "/platformLogos/gamecubeLogo.svg",
    "Wii": "/platformLogos/wiiLogo.svg",
    "Wii U": "/platformLogos/wiiULogo.svg",
    "Nintendo Switch": "/platformLogos/switchLogo.svg",
    "Nintendo Switch 2": "/platformLogos/switch2Logo.svg",
    "Game Boy": "/platformLogos/gameboyLogo.svg",
    "Game Boy Color": "/platformLogos/gameboycolorLogo.svg",
    "Game Boy Advance": "/platformLogos/gbaLogo.svg",
    "Nintendo DS": "/platformLogos/dsLogo.svg",
    "Nintendo 3DS": "/platformLogos/3dsLogo.svg",
    "PC": "/platformLogos/pcLogo.svg",
    "Sega Saturn": "/platformLogos/segasaturnLogo.svg",
    "Sega Dreamcast": "/platformLogos/segadreamcastLogo.svg",
    "Sega Mega Drive": "/platformLogos/segamegadriveLogo.svg",
    "Atari 2600": "/platformLogos/atari2600Logo.svg",
    "Atari Jaguar": "/platformLogos/atarijaguarLogo.svg",
    "Atari Lynx": "/platformLogos/atariolynxLogo.svg",
    "Neo Geo": "/platformLogos/neogeoLogo.svg",
};

export const formatLogoMap: Record<string, string> = {
    "Blu-ray": "/formatLogos/blurayLogo.svg",
    "Blu-ray 3D": "/formatLogos/bluray3dLogo.svg",
    "UHD Blu-ray": "/formatLogos/uhdblurayLogo.svg",
    "DVD": "/formatLogos/dvdLogo.svg",
    "VHS": "/formatLogos/vhsLogo.svg",
    "Betamax": "/formatLogos/betamaxLogo.svg",
    "VCD": "/formatLogos/vcdLogo.svg",
    "HD DVD": "/formatLogos/hddvdLogo.svg",
    "Laserdisc": "/formatLogos/laserdisclogo.svg",
};