import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CaseShelf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[theme(colors.background)] text-[theme(colors.foreground)]`}
      >
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1 overflow-hidden">
            {/* Header */}
            <header className="text-center p-4">
              <h1 className="text-4xl font-bold text-[theme(colors.foreground)]">
                CaseShelf
              </h1>
            </header>
            {/* Page Content */}
            <main className="flex-1 overflow-y-auto p-6 flex justify-center items-start">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
